# Generated by Django 4.2.1 on 2023-05-21 22:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calidad', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('NumeroCosecha', models.IntegerField()),
                ('Variedad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estadovinedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='vinedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dueno', models.TextField(max_length=50)),
                ('Nombre', models.TextField()),
                ('NumeroVin', models.IntegerField()),
                ('Ubicacion', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.estadovinedo')),
            ],
        ),
    ]
