# Generated by Django 4.2.1 on 2023-07-01 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('NumAnali', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('NomAnali', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Camionero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('ModeloCamion', models.CharField(max_length=50)),
                ('Patente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estadovinedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Franccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Articulo', models.CharField(max_length=50)),
                ('CantBot', models.IntegerField()),
                ('NumEmbo', models.CharField(max_length=50)),
                ('IniProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('FinProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('TipoBot', models.CharField(max_length=50)),
                ('TipoCaj', models.CharField(max_length=50)),
                ('TipoSepara', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TanqAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TanqueM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tan', models.IntegerField()),
                ('NumTanque', models.IntegerField()),
                ('LitrosTan', models.IntegerField()),
                ('LitrosFill', models.IntegerField()),
                ('LitrosPorcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vinedo',
            fields=[
                ('Dueno', models.TextField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('NumeroVin', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Ubicacion', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Altura', models.IntegerField(default=0)),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.estadovinedo')),
            ],
        ),
        migrations.CreateModel(
            name='TanqueE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoClari', models.BooleanField()),
                ('EstadoCrianza', models.BooleanField()),
                ('EstadoDespalillado', models.BooleanField()),
                ('EstadoEstrujado', models.BooleanField()),
                ('EstadoFermentacion', models.BooleanField()),
                ('EstadoMacerado', models.BooleanField()),
                ('EstadoTrasciego', models.BooleanField()),
                ('FechaClari', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaCrianza', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaDespa', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaEstru', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaFermen', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaMace', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaTra', models.DateTimeField(default=django.utils.timezone.now)),
                ('EstTanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanqact')),
                ('NumTanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanquem')),
            ],
        ),
        migrations.CreateModel(
            name='Pesada',
            fields=[
                ('NumeroPesada', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Tara', models.IntegerField()),
                ('PesoNeto', models.IntegerField()),
                ('PesoBruto', models.IntegerField()),
                ('FechaCosecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Eliminado', models.BooleanField()),
                ('Camionero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.camionero')),
                ('Varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.varietal')),
                ('Vinedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.vinedo')),
            ],
        ),
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('anoplant', models.IntegerField(default=0)),
                ('NumCuart', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('TipoRiego', models.CharField(default=None, max_length=50)),
                ('TelaAntigranizo', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Estado', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.estadovinedo')),
                ('NumVin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.vinedo')),
            ],
        ),
        migrations.CreateModel(
            name='ControlMadurez',
            fields=[
                ('NumContMad', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('IniProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('FinProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('NumCuar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cuartel')),
                ('NumVin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.vinedo')),
            ],
        ),
        migrations.AddField(
            model_name='camionero',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.estadovinedo'),
        ),
        migrations.CreateModel(
            name='AnalisisE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PH', models.CharField(default=None, max_length=50)),
                ('AcidezTotal', models.CharField(default=None, max_length=50)),
                ('NumAnali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.analisis')),
            ],
        ),
    ]
