# Generated by Django 4.2.1 on 2023-07-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisise',
            name='GradBaume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analisise',
            name='NumCuar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cuartel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisise',
            name='NumVin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.vinedo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analisise',
            name='AcidezTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analisise',
            name='PH',
            field=models.IntegerField(default=0),
        ),
    ]
