# Generated by Django 4.2.1 on 2023-06-05 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0002_alter_estadovinedo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantHileras', models.IntegerField()),
                ('NumCuart', models.IntegerField()),
                ('VarUva', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Hilera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantHileras', models.IntegerField()),
                ('NumHil', models.IntegerField()),
                ('NumCuart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cuartel')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumMov', models.IntegerField()),
                ('TanqInicio', models.IntegerField()),
                ('TanqFinal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TanqAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumTanque', models.IntegerField()),
                ('LitrosTan', models.IntegerField()),
                ('LitrosFill', models.IntegerField()),
                ('LitrosPorcentaje', models.IntegerField()),
                ('Cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cosecha')),
            ],
        ),
        migrations.AlterField(
            model_name='estadovinedo',
            name='Estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vinedo',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vinedo',
            name='Ubicacion',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumTrazabilidad', models.IntegerField()),
                ('EstadoCrianza', models.BooleanField()),
                ('EstadoDespalillado', models.BooleanField()),
                ('EstadoEstrujado', models.BooleanField()),
                ('EstadoFermentacion', models.BooleanField()),
                ('EstadoMacerado', models.BooleanField()),
                ('EstadoTrasciego', models.BooleanField()),
                ('MovTanques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.movimientos')),
                ('NumTanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanque')),
            ],
        ),
        migrations.CreateModel(
            name='TanqueEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoClari', models.BooleanField()),
                ('EstadoCrianza', models.BooleanField()),
                ('EstadoDespalillado', models.BooleanField()),
                ('EstadoEstrujado', models.BooleanField()),
                ('EstadoFermentacion', models.BooleanField()),
                ('EstadoMacerado', models.BooleanField()),
                ('EstadoTrasciego', models.BooleanField()),
                ('FechaClari', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaCrianza', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaDespa', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaEstru', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaFermen', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaMace', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaTra', models.DateTimeField(default=django.utils.timezone.now)),
                ('EstTanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanqact')),
                ('NumTanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanque')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumProc', models.IntegerField()),
                ('IniProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('FinProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('NumCose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cosecha')),
                ('VarUva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cuartel')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumPlanta', models.IntegerField()),
                ('CantPlantas', models.IntegerField()),
                ('PorcEnvero', models.IntegerField()),
                ('PorcFloracion', models.IntegerField()),
                ('Enfermedades', models.CharField(max_length=50)),
                ('HojaAmarilla', models.BooleanField()),
                ('Obs', models.CharField(max_length=50)),
                ('PesoMedBaya', models.IntegerField()),
                ('Temperatura', models.IntegerField()),
                ('NumHil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.hilera')),
            ],
        ),
        migrations.CreateModel(
            name='Embotellado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Articulo', models.CharField(max_length=50)),
                ('CantBot', models.IntegerField()),
                ('NumEmbo', models.CharField(max_length=50)),
                ('IniProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('FinProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('TipoBot', models.CharField(max_length=50)),
                ('TipoCaj', models.CharField(max_length=50)),
                ('TipoSepara', models.CharField(max_length=50)),
                ('IdProc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.proceso')),
                ('Tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanque')),
            ],
        ),
        migrations.AddField(
            model_name='cuartel',
            name='NumVin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.vinedo'),
        ),
    ]
