# Generated by Django 4.2.1 on 2023-06-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0003_cuartel_hilera_movimientos_tanqact_tanque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camionero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('ModeloCamion', models.CharField(max_length=50)),
                ('Patente', models.CharField(max_length=50)),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.estadovinedo')),
            ],
        ),
    ]
