# Generated by Django 4.2.1 on 2023-06-24 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0004_camionero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pesada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroPesada', models.IntegerField()),
                ('Tara', models.IntegerField()),
                ('PesoNeto', models.IntegerField()),
                ('PesoBruto', models.IntegerField()),
                ('FechaCosecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Camionero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.camionero')),
                ('Varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.varietal')),
                ('vinedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.vinedo')),
            ],
        ),
    ]
