# Generated by Django 4.2.1 on 2023-07-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0007_cuartel_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='NomBod',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
