# Generated by Django 4.2.1 on 2023-07-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0008_bodega_nombod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='NumBod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.bodega'),
            preserve_default=False,
        ),
    ]
