# Generated by Django 4.2.1 on 2023-06-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0008_vinedo_id_alter_cuartel_numvin_alter_pesada_vinedo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesada',
            name='Eliminado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
