# Generated by Django 4.2.1 on 2023-07-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0009_pesada_eliminado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesada',
            old_name='vinedo',
            new_name='Vinedo',
        ),
    ]
