# Generated by Django 4.2.1 on 2023-07-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0009_cronograma_numbod'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlmadurez',
            name='Varietal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.varietal'),
            preserve_default=False,
        ),
    ]
