# Generated by Django 4.2.1 on 2023-07-02 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0010_controlmadurez_varietal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='FinPrograma',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='InicioPrograma',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
