# Generated by Django 4.2.1 on 2023-07-01 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0010_rename_vinedo_pesada_vinedo'),
    ]

    operations = [

    ]
