# Generated by Django 4.2.1 on 2023-07-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0011_cronograma_finprograma_cronograma_inicioprograma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanquem',
            old_name='LitrosFill',
            new_name='LitrosFull',
        ),
        migrations.RenameField(
            model_name='tanquem',
            old_name='tan',
            new_name='TipoTanque',
        ),
    ]
