# Generated by Django 4.2.1 on 2023-07-01 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0011_analisis_controlmadurez_franccionado_tanquem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('NumAnali', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlMadurez',
            fields=[
                ('NumContMad', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('IniProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('FinProc', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Franccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Articulo', models.CharField(max_length=50)),
                ('CantBot', models.IntegerField()),
                ('NumEmbo', models.CharField(max_length=50)),
                ('IniProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('FinProc', models.DateTimeField(default=django.utils.timezone.now)),
                ('TipoBot', models.CharField(max_length=50)),
                ('TipoCaj', models.CharField(max_length=50)),
                ('TipoSepara', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TanqueE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoClari', models.BooleanField()),
                ('EstadoCrianza', models.BooleanField()),
                ('EstadoDespalillado', models.BooleanField()),
                ('EstadoEstrujado', models.BooleanField()),
                ('EstadoFermentacion', models.BooleanField()),
                ('EstadoMacerado', models.BooleanField()),
                ('EstadoTrasciego', models.BooleanField()),
                ('FechaClari', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaCrianza', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaDespa', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaEstru', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaFermen', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaMace', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaTra', models.DateTimeField(default=django.utils.timezone.now)),
                ('EstTanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanqact')),
            ],
        ),
        migrations.CreateModel(
            name='TanqueM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tan', models.IntegerField()),
                ('NumTanque', models.IntegerField()),
                ('LitrosTan', models.IntegerField()),
                ('LitrosFill', models.IntegerField()),
                ('LitrosPorcentaje', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='embotellado',
            name='IdProc',
        ),
        migrations.RemoveField(
            model_name='embotellado',
            name='Tanque',
        ),
        migrations.RemoveField(
            model_name='hilera',
            name='NumCuar',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='NumHil',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='NumCose',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='VarUva',
        ),
        migrations.RemoveField(
            model_name='tanque',
            name='Cosecha',
        ),
        migrations.RemoveField(
            model_name='tanqueestado',
            name='EstTanque',
        ),
        migrations.RemoveField(
            model_name='tanqueestado',
            name='NumTanque',
        ),
        migrations.RemoveField(
            model_name='trazabilidad',
            name='MovTanques',
        ),
        migrations.RemoveField(
            model_name='trazabilidad',
            name='NumTanque',
        ),
        migrations.RemoveField(
            model_name='cuartel',
            name='CantHileras',
        ),
        migrations.RemoveField(
            model_name='cuartel',
            name='VarUva',
        ),
        migrations.RemoveField(
            model_name='cuartel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pesada',
            name='id',
        ),
        migrations.AddField(
            model_name='cuartel',
            name='Estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.estadovinedo'),
        ),
        migrations.AddField(
            model_name='cuartel',
            name='TelaAntigranizo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuartel',
            name='TipoRiego',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='cuartel',
            name='anoplant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vinedo',
            name='Altura',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuartel',
            name='NumCuar',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='NumeroPesada',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Cosecha',
        ),
        migrations.DeleteModel(
            name='Embotellado',
        ),
        migrations.DeleteModel(
            name='Hilera',
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
        migrations.DeleteModel(
            name='Proceso',
        ),
        migrations.DeleteModel(
            name='Tanque',
        ),
        migrations.DeleteModel(
            name='TanqueEstado',
        ),
        migrations.DeleteModel(
            name='Trazabilidad',
        ),
        migrations.AddField(
            model_name='tanquee',
            name='NumTanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanquem'),
        ),
        migrations.AddField(
            model_name='controlmadurez',
            name='NumCuar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cuartel'),
        ),
        migrations.AddField(
            model_name='controlmadurez',
            name='NumVin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.vinedo', to_field='NumeroVin'),
        ),
    ]
