# Generated by Django 4.2.1 on 2023-07-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0012_analisis_controlmadurez_franccionado_tanquee_tanquem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuartel',
            old_name='NumCuar',
            new_name='NumCuart',
        ),
    ]
