# Generated by Django 4.2.1 on 2023-07-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0012_rename_litrosfill_tanquem_litrosfull_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanquem',
            name='LitrosFull',
        ),
        migrations.RemoveField(
            model_name='tanquem',
            name='LitrosPorcentaje',
        ),
        migrations.AddField(
            model_name='tanqact',
            name='LitrosFull',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanqact',
            name='LitrosPorcentaje',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tanqact',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.estadovinedo'),
        ),
    ]
