# Generated by Django 4.2.1 on 2023-07-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0013_remove_tanquem_litrosfull_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanquem',
            name='id',
        ),
        migrations.AlterField(
            model_name='tanquem',
            name='LitrosTan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tanquem',
            name='NumTanque',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tanquem',
            name='TipoTanque',
            field=models.IntegerField(default=0),
        ),
    ]
