# Generated by Django 4.2.1 on 2023-07-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0013_rename_numcuar_cuartel_numcuart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlmadurez',
            name='NumCuar',
        ),
        migrations.RemoveField(
            model_name='controlmadurez',
            name='NumVin',
        ),
    ]
