# Generated by Django 4.2.1 on 2023-07-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0014_remove_tanquem_id_alter_tanquem_litrostan_and_more'),
    ]

    operations = [

    ]
