# Generated by Django 4.2.1 on 2023-07-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0015_remove_tanquee_numtanque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanquee',
            name='NumTanque',
        ),
    ]
