# Generated by Django 4.2.1 on 2023-07-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0016_remove_tanquee_numtanque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanquee',
            name='FechaClari',
        ),
        migrations.RemoveField(
            model_name='tanquee',
            name='FechaCrianza',
        ),
        migrations.RemoveField(
            model_name='tanquee',
            name='FechaDespa',
        ),
        migrations.RemoveField(
            model_name='tanquee',
            name='FechaEstru',
        ),
        migrations.RemoveField(
            model_name='tanquee',
            name='FechaFermen',
        ),
        migrations.RemoveField(
            model_name='tanquee',
            name='FechaMace',
        ),
        migrations.RemoveField(
            model_name='tanquee',
            name='FechaTra',
        ),
    ]
