# Generated by Django 4.2.1 on 2023-07-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0017_remove_tanquee_fechaclari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTanq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoTanque', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tanquem',
            name='TipoTanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tipotanq'),
        ),
    ]
