# Generated by Django 4.2.1 on 2023-07-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0020_remove_tanqact_estado_remove_tanqact_litrosfull_and_more'),
    ]

    operations = [

    ]
