# Generated by Django 4.2.1 on 2023-07-08 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0025_pesada_bascula_alter_pesada_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanquee',
            name='PesaInicial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.pesada'),
            preserve_default=False,
        ),
    ]
