# Generated by Django 4.2.1 on 2023-07-09 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0030_alter_tanquem_numtanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanquee',
            name='TanqueMa',
            field=models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanquem'),
        ),
    ]
