# Generated by Django 4.2.1 on 2023-07-09 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0031_tanquee_tanquema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanquee',
            name='PesaInicial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.pesada'),
        ),
    ]
