# Generated by Django 4.2.1 on 2023-07-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0032_alter_tanquee_pesainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanqact',
            name='MovPosTanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientoposterior', to='GBAPP.tanquee'),
        ),
        migrations.AlterField(
            model_name='tanqact',
            name='MovPrevTanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientoprevio', to='GBAPP.tanquee'),
        ),
    ]
