# Generated by Django 4.2.1 on 2023-07-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0033_alter_tanqact_movpostanque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanqact',
            name='NumeroOrd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='NumeroO', to='GBAPP.tanquee', to_field='NumeroOrden'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tanquee',
            name='NumeroOrden',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
