# Generated by Django 4.2.1 on 2023-07-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0037_franccionado_cantcorcho_franccionado_cantetiqueta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuartel',
            old_name='NumCuart',
            new_name='id',
        ),
    ]
