# Generated by Django 4.2.1 on 2023-07-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0038_rename_numcuart_cuartel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuartel',
            name='NumCuartel',
            field=models.IntegerField(default=0),
        ),
    ]
