# Generated by Django 4.2.1 on 2023-07-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0040_remove_controlmadurez_finproc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='Cantidadmax',
            new_name='Cantidadmaxdia',
        ),
    ]
