# Generated by Django 4.2.1 on 2023-07-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0041_rename_cantidadmax_bodega_cantidadmaxdia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='Eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
