# Generated by Django 4.2.1 on 2023-07-16 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0042_cronograma_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='FechaIngreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
