# Generated by Django 4.2.1 on 2023-07-16 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0043_alter_cronograma_fechaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmadurez',
            name='IniProc',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='FinPrograma',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='InicioPrograma',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cuartel',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='franccionado',
            name='FinProc',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='franccionado',
            name='IniProc',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='FechaCosecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vinedo',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
