# Generated by Django 4.2.1 on 2023-07-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0044_alter_controlmadurez_iniproc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuartel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
