# Generated by Django 4.2.1 on 2023-07-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0045_alter_cuartel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmadurez',
            name='NumContMad',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='NumPrograma',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
