# Generated by Django 4.2.1 on 2023-07-17 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0046_alter_controlmadurez_numcontmad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesada',
            name='Cuartel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cuartel'),
            preserve_default=False,
        ),
    ]
