# Generated by Django 4.2.1 on 2023-07-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0047_pesada_cuartel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantBot', models.IntegerField(default=0)),
                ('CantSepara', models.IntegerField(default=0)),
                ('CantCorcho', models.IntegerField(default=0)),
                ('CantEtiqueta', models.IntegerField(default=0)),
            ],
        ),
    ]
