# Generated by Django 4.2.1 on 2023-07-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0048_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesada',
            name='Varietal',
        ),
    ]
