# Generated by Django 4.2.1 on 2023-07-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0052_remove_pesada_camionero_cronograma_camionero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanquee',
            name='NumeroMov',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
