# Generated by Django 4.2.1 on 2023-07-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0057_alter_estadovinedo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadovinedo',
            name='Estado',
            field=models.BooleanField(default=False),
        ),
    ]
