# Generated by Django 4.2.1 on 2023-07-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0058_alter_estadovinedo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadovinedo',
            name='Estado',
            field=models.CharField(max_length=50),
        ),
    ]
