# Generated by Django 4.2.1 on 2023-07-21 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0059_alter_estadovinedo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmadurez',
            name='NumCuar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cuartel', to_field='NumCuartel'),
        ),
        migrations.AlterField(
            model_name='cuartel',
            name='NumCuartel',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
