# Generated by Django 4.2.1 on 2023-07-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0062_alter_pesada_numeropesada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanquee',
            name='TipoAnali',
            field=models.IntegerField(default=0),
        ),
    ]
