# Generated by Django 4.2.1 on 2023-07-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0063_tanquee_tipoanali'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalisisE',
        ),
    ]
