# Generated by Django 4.2.1 on 2023-07-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0064_delete_analisise'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PH', models.IntegerField(default=0)),
                ('AcidezTotal', models.IntegerField(default=0)),
                ('GradBaume', models.IntegerField(default=0)),
                ('NumAnali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.analisis')),
                ('NumCuar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.cuartel')),
                ('NumVin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBAPP.vinedo')),
                ('TanqE', models.ManyToManyField(related_name='analisise_numeroo', to='GBAPP.tanquee')),
            ],
        ),
    ]
