# Generated by Django 4.2.1 on 2023-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0065_analisise'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='CantCajas',
            field=models.IntegerField(default=0),
        ),
    ]
