# Generated by Django 4.2.1 on 2023-07-22 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0066_stock_cantcajas'),
    ]

    operations = [
        migrations.AddField(
            model_name='franccionado',
            name='NumeroMov',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GBAPP.tanquee'),
            preserve_default=False,
        ),
    ]
