# Generated by Django 4.2.1 on 2023-07-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0067_franccionado_numeromov'),
    ]

    operations = [
        migrations.AddField(
            model_name='franccionado',
            name='CantCajas',
            field=models.IntegerField(default=0),
        ),
    ]
