# Generated by Django 4.2.1 on 2023-07-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBAPP', '0068_franccionado_cantcajas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanquee',
            name='EstadoFermen',
            field=models.BooleanField(default=False),
        ),
    ]
